// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {api} from '../models';

export function CreateBundle(arg1:string,arg2:string,arg3:Array<db.ContextRef>):Promise<db.Bundle>;

export function DeleteBundle(arg1:string):Promise<void>;

export function DuplicateBundle(arg1:string):Promise<db.Bundle>;

export function GetAPIURL():Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetBundle(arg1:string):Promise<db.Bundle>;

export function GetSettings():Promise<db.AppSettings>;

export function IssueKey(arg1:string):Promise<api.IssueKeyResult>;

export function ListBundles():Promise<Array<db.Bundle>>;

export function ListKeys():Promise<Array<db.AgentKey>>;

export function Quit():Promise<void>;

export function ResolveBundle(arg1:string):Promise<api.ResolveResult>;

export function RevokeKey(arg1:string):Promise<void>;

export function UpdateBundle(arg1:string,arg2:any,arg3:any,arg4:any):Promise<db.Bundle>;

export function UpdateSettings(arg1:any,arg2:any):Promise<db.AppSettings>;
