// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBundle(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateBundle'](arg1, arg2, arg3);
}

export function DeleteBundle(arg1) {
  return window['go']['main']['App']['DeleteBundle'](arg1);
}

export function DuplicateBundle(arg1) {
  return window['go']['main']['App']['DuplicateBundle'](arg1);
}

export function GetAPIURL() {
  return window['go']['main']['App']['GetAPIURL']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetBundle(arg1) {
  return window['go']['main']['App']['GetBundle'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function IssueKey(arg1) {
  return window['go']['main']['App']['IssueKey'](arg1);
}

export function ListBundles() {
  return window['go']['main']['App']['ListBundles']();
}

export function ListKeys() {
  return window['go']['main']['App']['ListKeys']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ResolveBundle(arg1) {
  return window['go']['main']['App']['ResolveBundle'](arg1);
}

export function RevokeKey(arg1) {
  return window['go']['main']['App']['RevokeKey'](arg1);
}

export function UpdateBundle(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateBundle'](arg1, arg2, arg3, arg4);
}

export function UpdateSettings(arg1, arg2) {
  return window['go']['main']['App']['UpdateSettings'](arg1, arg2);
}
